### ISSUE TITLE
Chirp Corrected Spectra?

### ISSUE THREAD

**Issue by buerviper** [glotaran/glotaran-1.5#37]
glotaran version: 1.5.1
    Operating System: Win 10

Description

After fitting a dataset, I want to access chirp corrected kinetics and chirp corrected transient spectra. The kinetics seem to be chirp corrected (as they all begin around a time zero without much delay to each other), but spectra at different times seem to be the original data - are chirp corrected spectra accessible somewhere?

**Comment by jsnel** [comment]
To the best of my knowledge (it has been a very long time since I last worked on Glotaran 1.5 and/or TIMP) we don't have the chirp corrected spectra available anywhere. The spectra you do see are the spectra calculated at time zero, being defined at the center of the fitted instrument response function. 

If it doesn't exist, I doubt we would make this functionality available in a future update of the Glotaran 1.5 branch as we have moved on to the development on a new Glotaran ecosystem developed in Python. But, I can discuss with my collaborators and see what the options are. 

Probably the best option is to move to the new, Python based, version of glotaran (aka pyglotaran), which will be released when it is ready, and it will be ready when it is deemed stable and feature complete. We will ping you on github when that is, feel free to subscribe.

**Comment by buerviper** [comment]
Yes, just found out about pyglotaran and cannot keep my feet still until it's released. 

Thanks for your detailed answer. But I just wonder: If chirp corrected kinetics are available, wouldn't chirp corrected spectra be somehow accessible (in my head, it's a 2D matrix then and it should be readable left-right and up-down)? But I understand that you probably don't have the time to investigate this in detail or to work on a fix. I'll just keep my fingers crossed that pyglotaran will have that feature implemented. :-)

**Comment by joernweissenborn** [comment]
Hi, I am the lead developer of pyglotaran. I can understand you can't wait for it, but I hope you understand that you don't want to publich science witch buggy software :)

But good news: we are preparing an alpha phase. If you really now what you are doing want acces to our latest features, you should subscribe at our new [mailing-list](https://groups.google.com/forum/#!forum/glotaran) and write an email with your question. The Mailinglist would be also be a better place for your question, because within the Glotaran project, we try to keep Github issues technical and rather answer user questions on the mailinglist.

Besides, with pyglotaran, what you want is easy to achieve. More details on the [mailing-list](https://groups.google.com/forum/#!forum/glotaran).
